plugins:
##    - jekyll-include-cache

remote_theme: 	"pmarsceill/just-the-docs"

color_scheme: schemeIniveo

# Footer content appears at the bottom of every page's main content
footer_content: "J Thompson 2021"

